### ISSUE TITLE
Course dashboard

### ISSUE THREAD

**Issue by crathbun428** [openedx/openedx-aspects#118]
```[tasklist]
### Feature: Course dashboard enablement
- [ ] https://github.com/openedx/openedx-aspects/issues/124
- [ ] https://github.com/openedx/openedx-aspects/issues/125
- [ ] https://github.com/openedx/openedx-aspects/issues/126
- [ ] https://github.com/openedx/openedx-aspects/issues/127
```
```[tasklist]
### Feature: Course dashboard enrollment content
- [ ] https://github.com/openedx/openedx-aspects/issues/128
- [ ] https://github.com/openedx/openedx-aspects/issues/129
- [ ] https://github.com/openedx/openedx-aspects/issues/130
- [ ] https://github.com/openedx/openedx-aspects/issues/131
- [ ] https://github.com/openedx/openedx-aspects/issues/132
- [ ] https://github.com/openedx/openedx-aspects/issues/133
```
```[tasklist]
### Feature: Course dashboard engagement content
- [ ] https://github.com/openedx/openedx-aspects/issues/134
- [ ] https://github.com/openedx/openedx-aspects/issues/135
- [ ] https://github.com/openedx/openedx-aspects/issues/136
- [ ] https://github.com/openedx/openedx-aspects/issues/137
- [ ] https://github.com/openedx/openedx-aspects/issues/138
- [ ] https://github.com/openedx/openedx-aspects/issues/139
```
```[tasklist]
### Feature: Course dashboard performance content
- [ ] https://github.com/openedx/openedx-aspects/issues/140
- [ ] https://github.com/openedx/openedx-aspects/issues/141
- [ ] https://github.com/openedx/openedx-aspects/issues/142
- [ ] https://github.com/openedx/openedx-aspects/issues/143
- [ ] https://github.com/openedx/openedx-aspects/issues/144
- [ ] https://github.com/openedx/openedx-aspects/issues/145
```
