### ISSUE TITLE
V1 reports in superset

### ISSUE THREAD

**Issue by jmakowski1123** [openedx/openedx-aspects#15]
**Aspects V1 Reports**

The goal of the V1 release is to deliver an MVP experience for instructional designers and course teams to access a curated set of reports and visualizations needed for analyzing course-level enrollment, engagement, and performance data all in one place and easily from the Open edX platform. Aspects will replace existing and [soon-to-be-deprecated Insights](https://discuss.openedx.org/t/deprecation-removal-remaining-insights-code-and-references/11922) with the aim of delivering a user-friendly analytics solution that offers near real-time data, and is modern, secure, easy to set up, less expensive to run, and much more extensible than the existing product. 

Because an Operator dashboard was developed for the Aspects beta in Superset that provides information in instance health, instance-level enrollment, courses, and organizations, we will include this dashboard with its current reports in this V1 release in order to ensure that instance administrators can access critical data while further discovery work is conducted to expand and improve these dashboards in a future release.

```[tasklist]
### Epics
- [ ] https://github.com/openedx/openedx-aspects/issues/117
- [ ] https://github.com/openedx/openedx-aspects/issues/118
- [ ] https://github.com/openedx/openedx-aspects/issues/119
- [ ] https://github.com/openedx/openedx-aspects/issues/120
- [ ] https://github.com/openedx/openedx-aspects/issues/121
```
