### ISSUE TITLE
Add new course comparison dashboard to Superset

### ISSUE THREAD

**Issue by crathbun428** [openedx/openedx-aspects#238]
**Use Cases**
As a Course Operator, I want to view data for…

- All courses on my instance with their org information, so I can identify the most and least popular, spot anomalies and trends
- All runs of a particular course, so that I can compare enrollment, engagement, and performance of each course run
- Comparing all runs of one course at a time
- All of my courses for those with permissions to only view information about their courses

**Requirements** (Will update this epic to show a task list with users stories that deliver the following epic requirements)
- A new Course Comparison Dashboard exists in Superset
- Depending on my permissions: 
   - I can see data for all courses/course runs on my instance. 
   - I can see all courses/course runs I have permissions to see. 
   - I can see nothing.
- For all courses/course runs or for all runs of ONE specified course, I can see:
   - Count of total current enrollees
   - Count of enrollees per enrollment track of the tracks available on my instance
   - Count of learners who have passed the course
   - Count of learners “Active within the last 7 days” count. These are learners who attempted a problem, watched a video, or viewed a page other than the course homepage and were active in the course within the last 7 days
- How are learners doing on the graded and ungraded problems in this course compared to another? Is this course more or less difficult than another?
   - Average % correct on the first attempt across the whole course (both graded and ungraded problems combined together)? 
- How is video engagement for this course? Are there any issues with the videos in this course that I need to be made aware of?
   - Percentage of video watched = (sum(distinct seconds of video watched)/total learners) / total seconds of all videos
   - Percentage of video rewatched = (sum(seconds of segments watched >1x)/total learners)/total seconds of all videos
   - Important context metrics for video: 
      - Count of how many videos there are in the course 
      - Average course video length

 **UX/UI Direction**
https://superset.aspects-beta.openedx.org/superset/dashboard/720/?native_filters_key=JHJJhrqMAPGQvtoIeycOusvLqmhkhL9xnYnFqUEZ_4VncdCu5x3r84UAUPUw26CB 

```[tasklist]
### Tasks
- [ ] https://github.com/openedx/openedx-aspects/issues/242
- [ ] https://github.com/openedx/openedx-aspects/issues/273
- [ ] https://github.com/openedx/openedx-aspects/issues/272
- [ ] https://github.com/openedx/openedx-aspects/issues/243
- [ ] https://github.com/openedx/openedx-aspects/issues/244
- [ ] https://github.com/openedx/openedx-aspects/issues/245
- [ ] https://github.com/openedx/openedx-aspects/issues/246
- [ ] https://github.com/openedx/openedx-aspects/issues/271
- [ ] https://github.com/openedx/openedx-aspects/issues/247
- [ ] https://github.com/openedx/openedx-aspects/issues/275
```
