### ISSUE TITLE
Show detailed information about selected problem in a course

### ISSUE THREAD

**Issue by crathbun428** [openedx/openedx-aspects#239]
**Use Cases**
As a course author, I want…

- To view detailed information about a single problem in the course, so that I’m able to better contextualize the average and median problem attempts and % correct data already presented in the course-level dashboards.

**Requirements** (Will update this epic to show a task list with users stories that deliver the following epic requirements)

- For any basic problem type: Single select, multi-select, dropdown, numerical input, text input) at a glance, a user can select a basic problem to view more detail about that individual problem.
   - Number of problem attempts per learner in box and whisker plot format ← to provide a fuller picture at a glance if outliers are swaying the average/median number of attempts for a given problem (on the Course Dashboard and At-Risk Learner Dashboard)
   - Show the most common answers on the Course Dashboard and At-Risk Learner Dashboard, so that course delivery team members can better understand from a glance where learners are getting things wrong / how learners are making sense of a question
      - For single select, dropdown problems, can I view a bar graph that shows the number of attempts per option (up to the 5 most common answers)? 
      - Discovery: For numerical input and text input problems, we need to test performance to see if rendering this data is anywhere 
near performant before implementing such detail. 
      - For multi-select, is it possible to render a different bar graph for this problem type? Showing a breakdown of the most common individual values selected?

```[tasklist]
### Tasks
- [ ] https://github.com/openedx/openedx-aspects/issues/265
- [ ] https://github.com/openedx/openedx-aspects/issues/266
- [ ] https://github.com/openedx/openedx-aspects/issues/267
- [ ] https://github.com/openedx/openedx-aspects/issues/268
- [ ] https://github.com/openedx/openedx-aspects/issues/269
```

**Comment by crathbun428** [comment]
Closing this issue as this work will be accomplished by: [https://github.com/openedx/openedx-aspects/issues/304](https://github.com/openedx/openedx-aspects/issues/304)
