### ISSUE TITLE
Compare courses sharing course-level tag(s)

### ISSUE THREAD

**Issue by crathbun428** [openedx/openedx-aspects#240]
**Use Cases**
As a course operator, I want to… 

- All courses about a particular topic, so I can spot most and least popular courses, or courses where learners are finishing or struggling to finish.

**Requirements**  (Will update this epic to show a task list with users stories that deliver the following epic requirements)
- I can filter the courses I’m comparing by topic using a Course tag filter
- Notes about tags:
   - If a user selects the Microbiology tag to apply it to a course and the taxonomy used for that instance has a hierarchy in place (example: Biology/Microbiology), both the Biology and Microbiology tags will be applied.
   - If a user wants to compare all courses with the Microbiology tag, they should be comparing all courses with the Microbiology tag regardless of any other tags that may be applied to those courses (for example: courses that are being analyzed may have just Biology/Microbiology applied, some may have the Biology/Microbiology and Biology/Microbiology/Microbiomes tags applied) and that’s OK, both should appear in the results for this filter.
   - If a user selects multiple course tags (for example 2 course tags) when creating a course tag filter, the results show any result that has tag value 1 OR tag value 2.
   - I can choose to view Courses or Course Runs.
   - I have an easy way to view all runs of ONE specified course.

**Notes**
- Once we start requiring tags in Aspects, we’ll be breaking compatibility with Quince. 
   - Need to make this known to users: If you’re on Tutor version Quince and before, don’t download this dashboard. 
   - If a user does download this dashboard anyway (only operators would see this dashboard). What does this look like when someone has the newest version of Aspects and an old (Quince or before version)?
   - Filter by course tag ← would appear but not work. There needs to be a message the user can view near the filter: This field will work for those running on Redwood or newer.
```[tasklist]
### Tasks
- [ ] https://github.com/openedx/openedx-aspects/issues/248
- [ ] https://github.com/openedx/openedx-aspects/issues/249
- [ ] https://github.com/openedx/openedx-aspects/issues/250
- [ ] https://github.com/openedx/openedx-aspects/issues/251
```

**Comment by Ian2012** [comment]
@crathbun428 can we mark this epic as finished?

**Comment by crathbun428** [comment]
@Ian2012 - One question before I close is if it would be too much trouble to fold that last bit of work I mentioned in our project slack channel into this:

**Comment by Ian2012** [comment]
@crathbun428 do we agree to close this task?

**Comment by crathbun428** [comment]
Yes - thank you!
