### ISSUE TITLE
UI improvements to de-clutter course-level dashboards

### ISSUE THREAD

**Issue by crathbun428** [openedx/openedx-aspects#241]
**Use Cases** 
As a course author, I want…

- Less charts and tables to look at on each dashboard, so that I don’t get overwhelmed looking at each dashboard and I’m able to easily find the data I need about my course 
- Each chart to be clearly titled and labeled, so that I’m confident what data I’m looking at and why

**Requirements** (Will update this epic to show a task list with users stories that deliver the following epic requirements)

- Streamline the tables in existing Course dashboards
   - Combine Problem Results and Problem Attempts tables (New name: Problem Attempts and Results) on the Engagement/Problems tab in the Course Dashboard and the At-Risk Learners Dashboard
   - Remove the Link column and make the Location and Name column value a link in the following tables (only if we can combine these two columns in a way that the link when clicked continues to direct the user to the appropriate place AND the user can click on the cell with the link to filter the dashboard as expected):
      - On the Course Dashboard and At-Risk Learner Dashboard:
         - Engagement/Problems: Problem Attempts and Results table
         - Engagement/Videos: Video Engagement
      - On the Individual Learner Dashboard:
         - Problems: Problem Results table
         - Videos tab: Partial and Full Video Views table - can we make the video location and name value a link to that video?
- Make things clearer for users.
   - Update labeling on video views per time segment chart
   - Update labeling on the page, problem, and video engagement dropoff graphs
- Can we test that: horizontal scroll is enabled for videos/problem/page engagement charts and video view charts for large courses with more than X bars? And if it doesn’t currently do this, can we look into if implementing a UI fix for these graphs is possible?
- Add and define an “Active within last 7 days” count to the Course Summary table (to the left of the Avg Course Grade column). Active learners are learners who attempted a problem, watched a video, or viewed a page other than the course homepage and were active in the last 7 days in the course

```[tasklist]
### Tasks
- [ ] https://github.com/openedx/openedx-aspects/issues/257
- [ ] https://github.com/openedx/openedx-aspects/issues/258
- [ ] https://github.com/openedx/openedx-aspects/issues/259
- [ ] https://github.com/openedx/openedx-aspects/issues/260
- [ ] https://github.com/openedx/openedx-aspects/issues/261
- [ ] https://github.com/openedx/openedx-aspects/issues/262
- [ ] https://github.com/openedx/openedx-aspects/issues/263
- [ ] https://github.com/openedx/openedx-aspects/issues/264
```
