### ISSUE TITLE
Plugin production configurations and testing

### ISSUE THREAD

**Issue by bmtcril** [openedx/openedx-aspects#52]
Each OARS Tutor plugin service needs to meet its own set of criteria and be tested before we can declare v1 ready for use. This epic is to collect those tickets in one place.

- [x] https://github.com/openedx/tutor-contrib-ralph/issues/6
- [x] https://github.com/openedx/tutor-contrib-oars/issues/19
- [x] https://github.com/openedx/tutor-contrib-clickhouse/issues/8
- [x] https://github.com/openedx/tutor-contrib-superset/issues/15

**Comment by Ian2012** [comment]
Can we close or update this ticket?
